on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: '.'
          TARGET: ${{ secrets.TARGET_DIR }}
